# Generated by Django 5.2.1 on 2025-06-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistEmocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocion', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('spotify_uri', models.CharField(max_length=100)),
            ],
        ),
    ]
