# Generated by Django 5.2.1 on 2025-06-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agematch', '0002_registroemocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroemocion',
            name='edad',
            field=models.IntegerField(default=25),
        ),
    ]
